image: docker
before_script:
  - apt-get update -qq && apt-get install -y -qq curl make dpkg
build_runq:
  script:
    - curl -o kernel/linux-image-5.9.8-arch1-cet_5.9.8-arch1-cet-1_amd64.deb --location "https://www.gitlab.com/api/v4/projects/22309799/jobs/artifacts/newcetapi-5.9.8/raw/linux-image-5.9.8-arch1-cet_5.9.8-arch1-cet-1_amd64.deb?job=build&job_token=$CI_JOB_TOKEN"
    - ls -l ./kernel
    - make -C kernel 
    - make release
  artifacts:
    paths:
      - runq-*.tar.gz